### ISSUE TITLE
SITE PUBLIC - performances - formulaires - améliorer vitesse de chargement après validation

### ISSUE THREAD

**Issue by cecileropital** [RustineLibre/RustineLibre#11]
https://rustinelibre.fr/reparateur/inscription

Pb de lenteur sur le form d'inscription des réparateurs. 
Sur le champ d'autocomplétion de la ville, la liste n'apparaît pas instantanément et les gens ont tendance à saisir le nom de la ville eux-mêmes. De ce fait, ils sont bloqués au moment de la validation.

**Comment by clementtalleu** [comment]
https://github.com/RustineLibre/RustineLibre/assets/11056924/33d48922-6f94-4a95-947a-8253fa2ee8b4

Il se passe 1 seconde entre le moment où on commence à taper le nom d'une ville et le moment où la liste apparaît, je vois pas trop ce qu'on peut rendre plus rapide. 

Et je pense pas qu'on puisse écrire le nom d'une ville complète avant que la liste déroulante apparaisse, à moins d'être vraiment rapide
