### ISSUE TITLE
ADMIN REPARATEURS + SUPER ADMIN : export CSV

### ISSUE THREAD

**Issue by cecileropital** [RustineLibre/RustineLibre#12]
**Besoin exprimé :** l’admin doit pouvoir télécharger un fichier CSV de l’ensemble de ses clients

**Solution envisagée :** ajouter un bouton “télécharger un csv” sur la rubrique utilisateurs + ajouter un bouton “télécharger un csv sur la rubrique réparateurs

**Comment by clementtalleu** [comment]
#24

**Comment by cecileropital** [comment]
Je ne vois pas le bouton sur l'admin

**Comment by clementtalleu** [comment]
<img width="1413" alt="Screenshot 2024-07-22 at 15 50 37" src="https://github.com/user-attachments/assets/82e5d59f-da0b-4d26-b4e4-76eb53cf90dc">

là c'est dans l'admin réparateur, 

pour le super admin tu le veux à quel niveau ? dans la partie "utilisateurs" ? et dans ce cas là récupérer tous les utilisateurs pour le super-admin ?

**Comment by cecileropital** [comment]
Oui, c'est ok sur l'admin du réparateur, merci.

Pour le super admin, tu peux le mettre sur la liste des "réparateurs" et sur celle des utilisateurs également stp.

**Comment by cecileropital** [comment]
Voici les données à exporter pour les super admin
Nom
Prénom
Email
Tel
Type de réparateur
Nom de la boutique 
Date d'arrivée sur la plateforme
Date de la dernière connexion

**Comment by f-jost** [comment]
@cecileropital les troix champs 
```
Type de réparateur
Nom de la boutique
Date d'arrivée sur la plateforme
```
concernent les réparateurs, pour les utilisateurs est ce que ces champs t'irai ? : 
```
Nom
Prénom
Email
Tel
Date de la dernière connexion
```
où as tu besoin de plus de champs ?
