### ISSUE TITLE
SITE PUBLIC -  Menu - remplacer “Devenir réparateur” par “Vous êtes réparateur ?”

### ISSUE THREAD

**Issue by cecileropital** [RustineLibre/RustineLibre#5]
Besoin exprimé : 
éviter la confusion avec des formations pour “devenir réparateur”

Solution envisagée : 
 remplacer “Devenir réparateur” par “Vous êtes réparateur ?”

**Comment by clementtalleu** [comment]
tu peux fermer ce ticket @Raphael-Marchese  ?
