### ISSUE TITLE
SUPER ADMIN - données statistiques sur les rendez-vous

### ISSUE THREAD

**Issue by cecileropital** [RustineLibre/RustineLibre#82]
**Besoin exprimé :** 

- avoir un listing de toutes les inscriptions et de tous les rendez-vous pris via la plateforme
- pouvoir télécharger un CSV

**Solution proposée :**

- ajout d'une rubrique statistiques avec le picto approprié : si https://fontawesome.com/icons/chart-simple?f=classic&s=solid
- reprendre la mise en page prévue dans la rubrique "réparateurs" (affichage sous forme de tableau)
**Nom** I **Prénom** I **Email** I **Date d'inscription** I **Date du rendez-vous** I **Prestation** I **Enseigne** 
- au dessus du tableau, conserver un moteur de recherche pour permettre au super admin de filtrer les données
- ajouter également la possibilité de filtrer les données sur une période et un bouton "Télécharger en CSV"
<img width="961" alt="Capture d’écran 2024-09-12 à 11 10 20" src="https://github.com/user-attachments/assets/ab0c3eaa-7ba4-41b5-a2b0-34ab6d779303">

**Comment by f-jost** [comment]
@cecileropital pour la colonne `Date d'inscription` je n'ai pas cette donnée dans la table des utilisateurs. Est ce que tu veux plutôt la valeur de la date de création du rendez vous ? (colonne `created_at` de la table `Appointment`) ?
