### ISSUE TITLE
Point sur la carte

### ISSUE THREAD

**Issue by marie-charlotte-woets** [RustineLibre/RustineLibre#91]
en tant que boss d’une enseigne
j’ai rentré l’adresse au moment de mon inscription, mais quand je vais sur la carte dans mes paramètres je vois ça
![Capture d’écran du 2024-09-22 16-39-17](https://github.com/user-attachments/assets/645c5f5b-92db-4ad3-b051-30b85a3f949a)

**Comment by davy-beauzil** [comment]
J'ai essayé de créer un compte réparateur, et celui est bien positionné sur la carte par rapport à l'adresse que je lui ai donné.
@marie-charlotte-woets est-ce que tu te souviens de l'adresse que tu as donné à ton réparateur pour que je puisse reproduire le problème ?

**Comment by marie-charlotte-woets** [comment]
j'ai dû mettre mon adresse je pense 53 rue du temple à Lens

**Comment by davy-beauzil** [comment]
@marie-charlotte-woets Je viens de réessayer avec l'adresse que tu m'as donné, mais la position sur la carte semble correspondre (voir photo).
Est-ce que tu peux re-tester pour voir si tu as toujours le problème ?

<img width="1504" alt="image" src="https://github.com/user-attachments/assets/85ef978b-3527-4dd7-b03e-510ad5ae1ba8">

**Comment by marie-charlotte-woets** [comment]
j'ai ajouté une nouvelle boutique et en effet je n'ai pas eu ce problème
peut-être que c'est parce que j'étais en navigation privée la première fois!
