### ISSUE TITLE
RDV sans compte client Rustine Libre - commentaire

### ISSUE THREAD

**Issue by marie-charlotte-woets** [RustineLibre/RustineLibre#93]
connecté en tant que réparateur
j’ai créé un rdv manuellement
 j'ai bien mis un commentaire mais je ne le vois pas

![Capture d’écran du 2024-09-22 16-58-07](https://github.com/user-attachments/assets/9a33c95f-6465-4641-b202-59e20ebabb88)
![Capture d’écran du 2024-09-22 16-58-21](https://github.com/user-attachments/assets/d9ce48f3-cdfa-4dcf-b166-9a691fbeb859)

**Comment by davy-beauzil** [comment]
Le bouton "Voir le commentaire" permet de voir le commentaire laissé par le cycliste lorsque c'est lui qui prend le rdv

**Comment by marie-charlotte-woets** [comment]
je ne comprends pas Davy, faudra qu'on en reparle
quand j'ajoute manuellement un rdv à un client sans compte en tant que réparateur, je peux mettre du texte dans le champ "détail de la demande", mais où puis je revoir ce texte? pour moi c'était le commentaire
