### ISSUE TITLE
RDV sans compte client Rustine Libre - modification du rdv

### ISSUE THREAD

**Issue by marie-charlotte-woets** [RustineLibre/RustineLibre#94]
connecté en tant que réparateur
j’ai créé un rdv manuellement

je ne peux modifier que l’heure et la date, pas le commentaire 

+ la modification de l'heure ou de la date ne fonctionnent pas - le menu ne se déroule pas

![Capture d’écran du 2024-09-22 16-56-38](https://github.com/user-attachments/assets/089efabf-20bc-4146-924e-eabac624da50)

**Comment by davy-beauzil** [comment]
C'est normal de ne pas pouvoir modifier le commentaire, celui-ci est transmis par le cycliste, donc non modifiable par le réparateur.
Concernant la modification du jour et de l'heure, je n'arrive pas à reproduire, mais je pense savoir pourquoi c'est arrivé.
Il est fort probable que le réparateur en question n'avait pas de créneaux disponibles à ce moment là. Ça expliquerait le menu vide.
