### ISSUE TITLE
Affichage carte / rayon de kilomètres / affichage nombre d’ateliers… 

### ISSUE THREAD

**Issue by marie-charlotte-woets** [RustineLibre/RustineLibre#97]
Quand, depuis HP :  je cherche LENS avec un rayon de 
5 km, j’ai un seul atelier qui s’affiche sur la carte et dans la liste => OK.
![1](https://github.com/user-attachments/assets/ca1e7a60-217e-467d-a961-bd4544880fd6)

10km : 2 ateliers dans la liste et dans ateliers sur la carte : OK
![2](https://github.com/user-attachments/assets/31444622-3a71-46ac-88e0-a91414d78281)

20 km et 30 km :  3 ateliers sur la carte, et 4 dans la liste… 
![3](https://github.com/user-attachments/assets/3c2cfc66-b4cd-4adc-ae17-7df61cf8758d)

40 km : bcp d’ateliers dans la liste, un seul sur la carte

![4](https://github.com/user-attachments/assets/4a1196fc-b048-47c2-b0eb-9108e1af2c7b)

**Comment by cecileropital** [comment]
@marie-charlotte-woets j'ai remonté ce bug il y a quelques semaines. @davy-beauzil a travaillé dessus la semaine dernière, il doit être mis sur la preprod prochainement
